name: CMake Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [devel, release/**]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [devel, release/**]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/actions/spelling/**"
      - ".github/ISSUE_TEMPLATE/**"
  repository_dispatch:
    types: [cmake-test]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CMake:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout F´ Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: ./.github/actions/setup
      - name: CMake Tests
        working-directory: ./cmake/test
        shell: bash
        run: |
          export CMAKE_INSTALL_DIRECTORY="${GITHUB_WORKSPACE}/tools-override"
          export PATH="${CMAKE_INSTALL_DIRECTORY}/bin:${PATH}"
          cmake --version
          pytest -s
